//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecomNevaSvyazTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public string NumberRequest { get; set; }
        public System.DateTime DateOfCreate { get; set; }
        public int PersonalAccount { get; set; }
        public int IDVidOfServices { get; set; }
        public int IDTypeOfServices { get; set; }
        public int IDStatus { get; set; }
        public string TypeOfEqupment { get; set; }
        public string DescriptionProblem { get; set; }
        public Nullable<System.DateTime> DateOfEnd { get; set; }
        public int IDTypeOfProblem { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual TypeOfProblem TypeOfProblem { get; set; }
        public virtual TypeOfServices TypeOfServices { get; set; }
        public virtual VidOfServices VidOfServices { get; set; }
    }
}
